#!/bin/bash

eval "$(dbus-launch --sh-syntax --exit-with-session)"

# fcitx
export XMODIFIERS="@im=fcitx"
export XIM=fcitx
export XIM_PROGRAM=fcitx
export QT_IM_MODULE=fcitx
export GTK_IM_MODULE=fcitx
fcitx
